version: '3.7'

services:
  marvel-api-node:
  container_name: marvel-api-node
    build: ${MARVEL_API_PATH:-.}/docker
    image: nexus.wako057.net:18442/marvel-api-node:1.0
    volumes:
      - ${MARVEL_API_PATH:-.}/:/var/nodejs/marvel-api-node/current
    expose:
      - 8080
    labels:
      traefik.frontend.rule: "Host: marvel-api.wako057.net"
      traefik.docker.network: "front"
      traefik.port: 8080
      traefik.frontend.entryPoints: http
    environment:
      NODE_PORT: 8080
      NODE_ENV: development
      ENV_LOG_LEVEL: trace
      ENV_LOG_DISABLE_STATUS: 1
    networks:
      front:
