version: '3.7'

services:
  marvel-api-node:
    build: docker/nodejs
    volumes:
      - ./nodejs:/var/nodejs/marvel-api-node/current
    ports:
      - 8080:8080
    environment:
      NODE_PORT: 8080
      NODE_ENV: development
      ENV_LOG_LEVEL: trace
      ENV_LOG_DISABLE_STATUS: 1
