version: '3.7'

services:
  marvel-api-node:
    build: docker/nodejs
    volumes:
      - ./nodejs:/var/nodejs/marvel-api-node/current
#    ports:
#      - 8080:8080
    expose:
      - 8080
    labels:
      traefik.frontend.rule: "Host: api-marvel.wako057.net"
      traefik.docker.network: "front"
      traefik.frontend.entryPoints: http
    environment:
      NODE_PORT: 8080
      NODE_ENV: development
      ENV_LOG_LEVEL: trace
      ENV_LOG_DISABLE_STATUS: 1
    networks:
      front:
      back:

  marvel-front-ng:
    build: docker/angular
    volumes:
      - ./angular:/var/nodejs/marvel-front-ng/current
#    ports:
#      - 4200:4200
    expose:
      - 4200
    labels:
      traefik.frontend.rule: "Host: marvel.wako057.net"
      traefik.docker.network: "front"
      traefik.frontend.entryPoints: http
    networks:
      front:
      back:

networks:
  front:
    name: front
    ipam:
      config:
        - subnet: 192.168.42.0/24
  back:
    name: back
    ipam:
      config:
        - subnet: 192.168.54.0/24


#    environment:
#      NODE_PORT: 8080
#      NODE_ENV: development
#      ENV_LOG_LEVEL: trace
#      ENV_LOG_DISABLE_STATUS: 1
